- untracked.xml
Change-Id: Ic27d822464fc9eae524afffaae56ec27e9cd1758
> untracked: Remove hardware/marvell/bt

- oss.xml
Fix compilation issue on Nougat 7.0 because Round Icon Resources are not supported.
> Move packages/apps/FMRadio to branch m-mr1

- untracked.xml
Change-Id: Ie62d17a46633f456b20bb26c6773a2dbc9910c43
Signed-off-by: Adrian DC <radian.dc@gmail.com>
> untracked: Remove irrelevant device/* and prebuilts paths

- LA.UM.5.7.r1.xml
> Update wlan-qc related repos

- LA.UM.6.4.r1.xml
- README.md
This PR can be merged when the 6.4 kernel will be ready.
Also update domain for Sony Developer World site.
> [master] Move to the new aosp/LA.UM.6.4.r1 kernel

- README.md
> [n-mr1_3.10] README.md: Update Sony Developer World domain

- README.md
> [n-mr1_3.18] README.md: Update Sony Developer World domain

- README.md
> [n-mr1_4.4] README.md: Update Sony Developer World domain

- untracked.xml
> untracked: Remove hardware/qcom/msm8998

- LA.UM.5.7.r1.xml
This reverts commit cde31ece26890a26c61c8a7eff0084ddac6d84b0.
> [8.0.0_r30] Revert "update Qcom WiFi to LA.UM.6.4.r1"

- LA.UM.5.7.r1.xml
This reverts commit cde31ece26890a26c61c8a7eff0084ddac6d84b0.
> [O-mr0] Revert "update Qcom WiFi to LA.UM.6.4.r1"

- oss.xml
- untracked.xml
We will use Googles json-c source from the hw/qcom/msm8998 repo
> manifest: remove json-c repo, readd hw/qcom/msm8998

- oss.xml
we can use that one present on hardware/qcom/msm8998
> manifest: remove time-services from oss.xml

- oss.xml
Signed-off-by: David Viteri <davidteri91@gmail.com>
> manifest: add releasekeys

- oss.xml
Signed-off-by: Pablo Mendez Hernandez <pablomh@gmail.com>
> Add CASH git

- oss.xml
Fix compile issue due to commit https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/commit/ac827c656647a41ba64cb27655bdff4b467e65eb on branch master
> [7.1.2_r36] Move ExtendedSettings to n-mr1 branch

- oss.xml
Fix build error when trying use kernel-4.9
> Copy os_pickup.bp for vendor/qcom/opensource/interfaces

- untracked_hardware.xml
Someone with a kumano device please build-test...
> [WIP] untracked_hardware: Remove unused sm8150 HALs

- untracked.xml
Reapplies commit c4e6d033786a19be0b7f28fc903b6634d5d2d2c2 which
was accidentally (?) reverted by eb6b8da40256d5b851a821e3d565a7c90b200205.
> untracked: remove dropped projects

- oss.xml
Our new telephony goodies such as ModemConfig are in this repository :)
> oss: Track SonyOpenTelephony

- nxp.xml
The repository has moved to a new location.[1]
[1] https://github.com/NXP/nfc-NXPNFCC_FW
> [master] nxp: Update NXP firmware git URL

- LA.UM.9.12.r1.xml
- devices.xml
Lets add all the needed changes to local_manifests files so we can build SODP for Edo devices.
> Welcome Edo (PDX203/6)

- untracked_devices.xml
- untracked_hardware.xml
- untracked_kernel.xml
@jerpelea When you get to it please perform the rebase trick on all these `rXX` branches and finally master. For cleanliness someone should probably check whether any of these commits are applicable to tags before r29.
> [local_manifests] [R r29] Untrack more unnecessary device/hardware/kernel repos

- K.P.1.0.r1.xml
While currently the techpacks and kernel itself is not fully finished the manifest should not change much if at all in the final version.
> [MASTER] Add manifest for 5.10 kernel

- qcom-sm8450.xml
This adds the required repos to manifest.
Signed-off-by: Martin Botka <martin.botka@somainline.org>
> [MASTER] qcom-sm8450.xml: Add SM8450 support (Nagara platform)

- qcom.xml
- untracked_devices.xml
- untracked_frameworks.xml
- untracked_hardware.xml
- untracked_kernel.xml
- untracked_packages.xml
Still heavily WIP, until I submit more PRs for the rest of the systems.
> Update untracked repositories for Android 14
