devices_3_18.xml

with this we use master only for 4.4 and newer and n-mr1 for 3.1x more easy to follow by external projects
and automatic scritps
Signed-off-by: David Viteri <davidteri91@gmail.com>

manifest_3.18: use n-mr1 for sepolicy

---

oss.xml

Recent commits into Xperia ExtendedSettings app introduced code changes not compatible with
legacy Android 6.0 Marshmallow. As a result it is not possible to build this legacy Android
due to build errors while building this app.
Most notably [this commit](https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/commit/2594556917f53f8ec2b71e04dbde8567b4d66e2a), which added ```android:directBootAware="true"``` into AndroidManifest.xml. This flag is not recognized in AOSP 6.0.
As this application is not essential to AOSP build, this commit removes the app from AOSP project list.
Signed-off-by: Vladimir Zahradnik <vladimir.zahradnik@gmail.com>

remove Xperia ExtendedSettings app

---

LA.UM.5.7.r1.xml
untracked.xml

Camera HAL was added back to AOSP and we don't need this because we use our own Camera HAL.
And also remove wahoo prebuilt kernel and depricated hardware/qcom/msm8x09.

[master] Do not track AOSP Camera HAL

---

LA.UM.5.7.r1.xml

This commit fix issue https://github.com/sonyxperiadev/bug_tracker/issues/70

[N-mr1_4.4] Revert "update Qcom WiFi to LA.UM.6.4.r1"

---

LA.UM.5.7.r1.xml

This reverts commit cde31ece26890a26c61c8a7eff0084ddac6d84b0.

[8.0.0_r33] Revert "update Qcom WiFi to LA.UM.6.4.r1"

---

oss.xml

the android-7.1.1_r55 branch is a legacy branch that will hold the
pre HIDL fingerprint
Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

move fingerprint to the android-8.1.1_r55 branch

---

oss.xml

* Soong is unable to include 'interfaces' folder without it.

Copy os_pickup.bp for vendor/qcom/opensource/interfaces

---

untracked.xml

At least for me it slows me traversing (tab-tab) the hierarchy through kernel/msm/sony*.

[master] Remove kernel/tests project

---

devices.xml

After removing the hardware/qcom/sdm845/data/ipacfg-mgr we lost the
hardware/qcom/sdm845/Android.mk file that was sourced (linked) from there,
so take a similar enough one from here.
It's a hack, but I cannot think of a better compromise for now.
Signed-off-by: Pablo Mendez Hernandez <pablomh@gmail.com>

Make hardware/qcom/sdm845 subdirs usable again

---

qcom.xml

The AOSP master branch contains commits which could potentially be incompatible with the version of Android that being built. 
Removing the master revision from these projects will allow them to default to the branch that the project was initialised with.
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/474

Remove master revision from AOSP projects

---

qcom.xml

The AOSP master branch contains commits which could potentially be
incompatible with the version of Android that being built.
Removing the master revision from these projects will allow them to
default the branch that the project was initialised with.

[master, android-10] Remove master revision from AOSP projects

---

untracked_devices.xml

This device depends on other repositories that have also been untracked,
just like all other Pixel devices.
DONOTMERGE: I am on the P4 tags (for no good reason really, it's probably quite close to P3 and others). This can stay open untill Google _finally_ merges all devices into a single tag.

[DONOTMERGE] untracked_devices: Untrack coral, which was added in the latest monthly.

---

LA.UM.7.1.r1.xml

This techpack is useful to get advanced rmnet functionality, such as proper
offloading, qos and battery savings.

[MANIFESTS] LA.UM.7.1.r1: Add data-kernel techpack driver

---

LA.UM.7.1.r1.xml

This techpack is useful to get advanced rmnet functionality, such as proper
offloading, qos and battery savings.
This commit is missing on branch android-10.0.0_r15. Without it, the kernel fails to build.

[android-10.0.0_r15] LA.UM.7.1.r1: Add data-kernel techpack driver

---

qcom.xml

The LA.UM.8.1.r1 codebase is the one that we want to use, since
the kernel vidc driver will be upgraded to it very soon.
This HAL is anyway working with the 7.1.r1 driver so no
functional issues will appear while the kernel gets migrated.
As for the rest, the new SDM660-libion HAL is what we now want
for legacy SoCs on kernel 4.14 in order to get hardware enc/dec
working through Venus.

[LOCAL_MANIFESTS] Add legacy venus HAL and switch SM8150 to 8.1

---

qcom.xml

~DONOTMERGE: These patches depend on v4 blobs.~ v4 blobs are almost here :)
Our compatibility patches have been applied on top of a CAF 8.1 branch
and new blobs will be provided with the v4 release. These newer tags
provide more features/fixes and allow us to switch to composer 2.3.

qcom: Switch display interfaces and HAL to LA.UM.8.1.r1 codebase.

---

qcom.xml

OEM v6 includes blobs for new camera and kernel driver upgrade has been merged.
So lets switch to new HAL.

Qcom: Switch camera to new HAL.

---

qcom.xml

v6 includes blobs for new camera and kernel driver upgrade has been merged.
So lets switch to new HAL.
cherry-picked from master without the commit it is no longer possible to build current android-10.0.0_r33.

[android-10.0.0_r33] qcom: Switch camera to new HAL

---

qcom.xml

The tag update is needed for new IMS features.

[WIP] qcom: Update CAF telephony to LA.UM.8.2.1.r1

---

qcom.xml

Add the sound trigger HAL to vendor/qcom/opensource/st-hal
now that it compiles and can run just fine.
Test: Build OK
Depends on https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-st-hal/pull/1

[LOCAL_MANIFESTS] qcom.xml: Add sound trigger HAL

---

qcom.xml
untracked_hardware.xml

The display, media and ipa hals actively used by the project were placed into subdirectories of the default hal locations.
This was done for the sole purpose of not having them automatically included, so that they can be explicitly included in device/sony/common/hardware/qcom/Android.mk.
That unfortunately introduced a nasty side effect, which is that 'repo status' would always report that the build tree is dirty.
Avoid that nastiness by opting to move the hals to a different location, and adding build guards to them to avoid erroneous inclusion.
With this it is also possible to untrack the default display and media hals.

untracked/qcom: do away with default hal locations

---

qcom.xml
untracked_hardware.xml

Instead of relying on aosp gps hals, which are not always in sync with oss location, switch to using hal from caf.
Also move the hal to vendor to make it inline with the other hals.

[DNM] untracked/qcom: switch to own gps hal

---

LA.UM.7.1.r1.xml

All our phones have been tested to deliver similar or better WiFi
performance on the sm8150 8.1 branches, and the newer tag is a
requirement for Seine.
Together with:
https://github.com/sonyxperiadev/kernel/pull/2292
https://github.com/sonyxperiadev/vendor-qcom-opensource-wlan-qcacld-3.0/pull/26

[LOCAL_MANIFESTS] vendor-qcom-opensource-wlan: Update qcacld driver to 8.1 branch

---

external.xml

As requested, resubmitted against the current branch and avoid clashing in the
destination directories: it will delete the old exfat directory and create the new exfatprogs:
```
$ repo sync -j8 --current-branch --no-tags
Fetching projects:   1% (11/707)
. . .
vendor/external/exfat: Deleting obsolete checkout.
. . .
Checking out projects: 100% (707/707), done.
repo sync has finished successfully.
$ ls vendor/external/ | grep exfat
exfatprogs
```
(Proper history of this PR can be checked at https://github.com/sonyxperiadev/local_manifests/pull/103).

[android-10.0.0_r41] external: move exfat support tooling from relan to exfatprogs

---

oss.xml

As was recommended in https://github.com/sonyxperiadev/vendor-sony-oss-projection/pull/6 we
should drop projection repo as blanc wont be getting Android R.

[DNM][11.0.0_r1] oss.xml: Remove projection repo

---

broadcom.xml
untracked_hardware.xml

The bt-fm repo was originally intended for FM radio related things, but never used in recent Android versions.
The wlan repo contained firmware and configs for bcmdhd devices, but as of k4.9, all bcmdhd devices have been ported to brcmfmac.
The file `hardware/broadcom/wlan/bcmdhd/config/config-bcm.mk` is lazily `-include`d by files in `vendor/broadcom`, so removing the hardware/broadcom/wlan repo will stop it from overwriting our own wifi config overlay files.

Remove unused broadcom repos

---

oss.xml

We sadly no longer can provide support for all the legacy devices.
Thus lets delete this repo as it wont be longer required.
Also this repo just contains USB HAL that for things that
dont support /sys/class/dual_role_usb

oss.xml: Drop interfaces repo

---

qcom.xml

Upon popular request, part 3 of https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/pull/8 and https://github.com/sonyxperiadev/device-sony-common/pull/791

[MANIFESTS] [3/3] [R] Switch primary audio HAL to r branch (based on 9.11 tag)

---

qcom.xml

The master branch of vendor.qcom.opensource.bluetooth has a patch to remove references to libhidltransport, which was still present in android-9.0.0_r46. This causes the following error when trying to build AOSP:
```
system/libhidl/transport/include/hidl/LegacySupport.h:69: error: undefined reference to 'android::hardware::configureRpcThreadpool(unsigned long, bool)'
system/libhidl/transport/include/hidl/LegacySupport.h:76: error: undefined reference to 'android::hardware::joinRpcThreadpool()'
```
See https://github.com/sonyxperiadev/vendor-qcom-opensource-bluetooth/issues/3 and https://github.com/sonyxperiadev/bug_tracker/issues/474

vendor.qcom.opensource.bluetooth: set to p-mr1 branch

---

untracked_hardware.xml

This will be needed in order to disable `TARGET_BOARD_AUTO`
as some of this repos are picked wrongly by `yoshino `after the removal.
This needs to be specially tested on `yoshino`, for which I don't have availability.

[master] Untrack unused AOSP QCOM repos

---

broadcom.xml

As of Android 11 we don't support any Broadcom WiFi enabled devices thus lets remove the repos.
This needs to be completely tested that it doesn't break anything.

[R] Remove broadcom wlan repo.

---

untracked_hardware.xml

Android 11 r29 tags added some new HALs that we don't use.
---
Note that we also seem to have `sm7150` and `sm8150p` in-tree, both unused. Should we untrack those as well?

hardware: Untrack sm7250 repos

---

untracked_devices.xml

AOSP dropped the kernel for these devices on r32, presumably while moving to `kernel/prebuilts/...`.
---
@jerpelea please create an `android-11.0.0_r32` branch and update the target branch before merging this!
Disclaimer: r32 was not build/run-tested yet, this only gets my mirror to sync properly against it.

[local_manifests] [R r32] untracked_devices: Remove bramble/redfin kernels for 11.0.0_r32

---

qcom.xml

The `r-mr1` branch contains an older failed port attempt on top of 9.11 branches, while the actual development efforts have been made on `aosp/LA.UM.9.12.r1` (though that branch is based on 9.15 KAMORTA).
The st-hal has been updated to newer tags to follow suit.

qcom: Point audio HALs to aosp/LA.UM.9.12.r1

---

untracked_devices.xml

This was missed during the r32 rebase.
Fixes: 0b3c5a8 ("untracked_devices: Remove bramble/redfin kernels for 11.0.0_r32")

[local_manifests] [R-r32/master] untracked_devices: Untrack redbull-kernel

---

LA.UM.9.12.r1.xml

Don't merge this yet! Edo is doing happy (albeit eating tons of power) on software encoding/decoding, but with vidc camera recording crashes in various ways (buffer allocation failures, segfaults deep in the CHI). This should at least get us started on a common debugging ground.

[S] LA.UM.9.12: Add kernel video-driver repo

---

qcom-sm8450.xml

These HALs are utilized by Nagara platform running 5.10 kernel
Depends on https://github.com/sonyxperiadev/vendor-qcom-opensource-display/pull/5 to build
Signed-off-by: Martin Botka <martin.botka@somainline.org>

qcom-sm8450.xml: Add Display and media HALs for 5.10

---

untracked_devices.xml
untracked_packages.xml

@ShujathMoh we typically comment out repos that _still exist_ but break the build, and document (contrary to what @Haxk20 suggested in [1]) what depends on them.
Also, what broke for you when missing `device/common` and `device/generic/art`? I just performed a successful build without these.
[1]: https://github.com/sonyxperiadev/local_manifests/pull/138#pullrequestreview-1075478010

[13] Cleanup

---

untracked_devices.xml

Untrack the google devices felix, lynx and tangorpro.
They break the building of aosp.
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/801

[13] Untrack google devices

---

untracked_frameworks.xml
untracked_hardware.xml
untracked_kernel.xml
untracked_packages.xml

In #148 - a WIP PR - a bunch of annoying repos were untracked to see if they could finally be skipped.  Unfortunately it turns out most of these have to be restored to make the build succeed.
In addition `bash` history suggests that I went through the same hopes and process last year.

Re-track some necessary repos for AOSP 14

---

oss.xml

Starting with Android 11 (and up) we always target the `master` branch for our `fingerprint` repo, making it impossible to merge features and fixes for future Android versions without breaking older Android versions (in this case mandatory to support newer kernels), as is the case with: https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/76
In order to prevent Android 11 from using code a new `r-mr1` branch was created, pointing to the commit _before_ that PR was merged.  This means Android 11 will now miss out on any future improvements we might push to the `master` branch though.

[Android 11] oss: Point `fingerprint` repository to `r-mr1` branch

---

qcom-sm8550.xml
qcom.xml

1. Provide HALs which will be used for devices running on kernel 5.15.
2. Bump interfaces repo to LA.QSSI.13.0.r1. Required for the latest HALs. Backwards compatible with all previous versions. I hope one day we will align all the other repositories.

[Android 13] qcom-sm8550: Provide HALs for kernel 5.15

---

untracked_devices.xml
untracked_kernel.xml

This PR contains two commits.
1, Removing non existent devices from untracked_devices.xml which prevents users from syncing due to non existent  error.
2. Tracking back kernel/prebuilts/6.1/arm64 and kernel/prebuilts/6.1/x86-64 as packages/modules/Virtualization/microdroid depends on it. This prevents users from building with the below error : 
error: packages/modules/Virtualization/microdroid/initrd/Android.bp:43:1: "microdroid_gki-android14-6.1_initrd_gen_arm64" depends on undefined module "microdroid_gki_modules-6.1-arm64".
Or did you mean ["libmicrodroid_metadata_proto_rust"]?
error: packages/modules/Virtualization/microdroid/initrd/Android.bp:54:1: "microdroid_gki-android14-6.1_initrd_gen_x86_64" depends on undefined module "microdroid_gki_modules-6.1-x86_64".
Or did you mean …

Android 14.0.0 r30
